"""antispam

Revision ID: 0b88ffe4d887
Revises: 63a14f1e4e5b
Create Date: 2026-09-19 15:31:19.068562+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b88ffe4d887'
down_revision: Union[str, Sequence[str], None] = '63a14f1e4e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_violations',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rule', sa.String(length=32), nullable=False),
    sa.Column('count', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('notified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk_filter_violations_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'user_id', 'rule', name=op.f('pk_filter_violations'))
    )
    op.create_table('forbidden_words',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk_forbidden_words_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forbidden_words')),
    sa.UniqueConstraint('chat_id', 'word', name='uq_forbidden_words_chat_word')
    )
    op.create_index('ix_forbidden_words_chat', 'forbidden_words', ['chat_id'], unique=False)
    op.create_table('forward_whitelist',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk_forward_whitelist_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forward_whitelist')),
    sa.UniqueConstraint('chat_id', 'source_type', 'source_id', name='uq_forward_whitelist_source')
    )
    op.create_index('ix_forward_whitelist_chat', 'forward_whitelist', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_forward_whitelist_chat', table_name='forward_whitelist')
    op.drop_table('forward_whitelist')
    op.drop_index('ix_forbidden_words_chat', table_name='forbidden_words')
    op.drop_table('forbidden_words')
    op.drop_table('filter_violations')
    # ### end Alembic commands ###
