"""activity statistics

Revision ID: 11209f2b35ed
Revises: 0b88ffe4d887
Create Date: 2026-09-19 15:58:36.282404+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11209f2b35ed'
down_revision: Union[str, Sequence[str], None] = '0b88ffe4d887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_daily',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('messages', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk_activity_daily_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'user_id', 'day', name=op.f('pk_activity_daily'))
    )
    op.create_index('ix_activity_chat_day', 'activity_daily', ['chat_id', 'day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activity_chat_day', table_name='activity_daily')
    op.drop_table('activity_daily')
    # ### end Alembic commands ###
