"""moderation

Revision ID: 212aebcfb4bb
Revises: 97c2a1014cf0
Create Date: 2026-09-19 14:46:50.841555+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212aebcfb4bb'
down_revision: Union[str, Sequence[str], None] = '97c2a1014cf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('punishments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_chat_target', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk_punishments_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_punishments'))
    )
    op.create_index('ix_punishments_active', 'punishments', ['chat_id', 'user_id'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_index('ix_punishments_chat_created', 'punishments', ['chat_id', 'created_at'], unique=False)
    op.create_index('ix_punishments_until', 'punishments', ['until'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_table('warnings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk_warnings_chat_id_chats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_warnings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warnings'))
    )
    op.create_index('ix_warnings_active', 'warnings', ['chat_id', 'user_id', 'expires_at'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('ix_warnings_chat_created', 'warnings', ['chat_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_warnings_chat_created', table_name='warnings')
    op.drop_index('ix_warnings_active', table_name='warnings', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('warnings')
    op.drop_index('ix_punishments_until', table_name='punishments', postgresql_where=sa.text('is_active'))
    op.drop_index('ix_punishments_chat_created', table_name='punishments')
    op.drop_index('ix_punishments_active', table_name='punishments', postgresql_where=sa.text('is_active'))
    op.drop_table('punishments')
    # ### end Alembic commands ###
