"""triggers

Revision ID: 39dc1706bc1a
Revises: 212aebcfb4bb
Create Date: 2026-09-19 15:05:25.321552+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39dc1706bc1a'
down_revision: Union[str, Sequence[str], None] = '212aebcfb4bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_contents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('file_id', sa.String(length=256), nullable=True),
    sa.Column('file_unique_id', sa.String(length=128), nullable=True),
    sa.Column('keyboard', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_contents'))
    )
    op.create_table('triggers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('display_key', sa.String(length=128), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('cooldown', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('hits', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk_triggers_chat_id_chats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_id'], ['message_contents.id'], name=op.f('fk_triggers_content_id_message_contents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_triggers')),
    sa.UniqueConstraint('chat_id', 'key', name='uq_triggers_chat_key')
    )
    op.create_index('ix_triggers_enabled', 'triggers', ['chat_id'], unique=False, postgresql_where=sa.text('is_enabled'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_triggers_enabled', table_name='triggers', postgresql_where=sa.text('is_enabled'))
    op.drop_table('triggers')
    op.drop_table('message_contents')
    # ### end Alembic commands ###
