"""reputation and ranks

Revision ID: 63a14f1e4e5b
Revises: 78e28375f3c3
Create Date: 2026-09-19 15:24:07.993859+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a14f1e4e5b'
down_revision: Union[str, Sequence[str], None] = '78e28375f3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reputation_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('value_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reputation_history'))
    )
    op.create_index('ix_reputation_history_actor', 'reputation_history', ['chat_id', 'actor_id', 'created_at'], unique=False)
    op.create_index('ix_reputation_history_user', 'reputation_history', ['chat_id', 'user_id', 'created_at'], unique=False)
    op.create_table('ranks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk_ranks_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranks')),
    sa.UniqueConstraint('chat_id', 'name', name='uq_ranks_chat_name'),
    sa.UniqueConstraint('chat_id', 'threshold', name='uq_ranks_chat_threshold')
    )
    op.create_index('ix_ranks_chat_threshold', 'ranks', ['chat_id', 'threshold'], unique=False)
    op.create_table('reputation',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk_reputation_chat_id_chats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_reputation_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'user_id', name=op.f('pk_reputation'))
    )
    op.create_index('ix_reputation_top', 'reputation', ['chat_id', sa.literal_column('value DESC')], unique=False)
    op.create_table('user_ranks',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rank_id', sa.BigInteger(), nullable=True),
    sa.Column('achieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk_user_ranks_chat_id_chats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], name=op.f('fk_user_ranks_rank_id_ranks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('chat_id', 'user_id', name=op.f('pk_user_ranks'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ranks')
    op.drop_index('ix_reputation_top', table_name='reputation')
    op.drop_table('reputation')
    op.drop_index('ix_ranks_chat_threshold', table_name='ranks')
    op.drop_table('ranks')
    op.drop_index('ix_reputation_history_user', table_name='reputation_history')
    op.drop_index('ix_reputation_history_actor', table_name='reputation_history')
    op.drop_table('reputation_history')
    # ### end Alembic commands ###
