"""welcome and captcha

Revision ID: 78e28375f3c3
Revises: 39dc1706bc1a
Create Date: 2026-09-19 15:15:43.583848+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78e28375f3c3'
down_revision: Union[str, Sequence[str], None] = '39dc1706bc1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captcha_sessions',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('answer', sa.String(length=64), nullable=False),
    sa.Column('attempts_left', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk_captcha_sessions_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'user_id', name=op.f('pk_captcha_sessions'))
    )
    op.create_index('ix_captcha_expires', 'captcha_sessions', ['expires_at'], unique=False)
    op.create_table('welcome_messages',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('last_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk_welcome_messages_chat_id_chats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_id'], ['message_contents.id'], name=op.f('fk_welcome_messages_content_id_message_contents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk_welcome_messages'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('welcome_messages')
    op.drop_index('ix_captcha_expires', table_name='captcha_sessions')
    op.drop_table('captcha_sessions')
    # ### end Alembic commands ###
