"""settings and texts

Revision ID: 97c2a1014cf0
Revises: d6971fff5bde
Create Date: 2026-09-19 11:15:10.955047+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97c2a1014cf0'
down_revision: Union[str, Sequence[str], None] = 'd6971fff5bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_texts',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('lang', sa.String(length=8), server_default='ru', nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', 'lang', name=op.f('pk_global_texts'))
    )
    op.create_table('settings_audit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings_audit'))
    )
    op.create_index('ix_settings_audit_chat_created', 'settings_audit', ['chat_id', 'created_at'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_settings'))
    )
    op.create_table('chat_settings',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk_chat_settings_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'key', name=op.f('pk_chat_settings'))
    )
    op.create_table('chat_texts',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('lang', sa.String(length=8), server_default='ru', nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk_chat_texts_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'key', 'lang', name=op.f('pk_chat_texts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_texts')
    op.drop_table('chat_settings')
    op.drop_table('system_settings')
    op.drop_index('ix_settings_audit_chat_created', table_name='settings_audit')
    op.drop_table('settings_audit')
    op.drop_table('global_texts')
    # ### end Alembic commands ###
