"""chats, users, chat_members

Revision ID: d6971fff5bde
Revises: 
Create Date: 2026-09-19 11:02:10.275693+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6971fff5bde'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('bot_status', sa.String(length=16), nullable=False),
    sa.Column('bot_permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('added_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('migrated_to_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk_chats'))
    )
    op.create_index('ix_chats_status', 'chats', ['status'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    op.create_index('ix_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=False, postgresql_where=sa.text('username IS NOT NULL'))
    op.create_table('chat_members',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.SmallInteger(), server_default='10', nullable=False),
    sa.Column('tg_status', sa.String(length=16), nullable=False),
    sa.Column('tg_permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('messages_total', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], name=op.f('fk_chat_members_chat_id_chats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_chat_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'user_id', name=op.f('pk_chat_members'))
    )
    op.create_index('ix_chat_members_activity', 'chat_members', ['chat_id', sa.literal_column('messages_total DESC')], unique=False)
    op.create_index('ix_chat_members_staff', 'chat_members', ['chat_id', 'role'], unique=False, postgresql_where=sa.text('role > 10'))
    op.create_index('ix_chat_members_user_id', 'chat_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_members_user_id', table_name='chat_members')
    op.drop_index('ix_chat_members_staff', table_name='chat_members', postgresql_where=sa.text('role > 10'))
    op.drop_index('ix_chat_members_activity', table_name='chat_members')
    op.drop_table('chat_members')
    op.drop_index('ix_users_username_lower', table_name='users', postgresql_where=sa.text('username IS NOT NULL'))
    op.drop_table('users')
    op.drop_index('ix_chats_status', table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
